### ISSUE TITLE
Your documentation on Blazor Components location

### ISSUE THREAD

**Issue by kevingates** [ShaunCurtis/Blazor.ExploreRendering#1]
Hi there,

I found and appreciate your work on the documents regarding InteractiveAuto, global versus per page, etc. You mention the components and how you had a separate project for that before. However, your example code does not show that pattern. Have you changed how you like to do things or did the Solution just not contain it for this example app yet?

We're getting ready to start an enterprise app in Blazor 8 and so I wanted to make informed judgments as we go forward.

Many thanks!

**Comment by ShaunCurtis** [comment]
See:
 -  https://github.com/ShaunCurtis/Blazor.Interactivity
 - https://github.com/ShaunCurtis/Blazr.RenderState
